# Generated by Django 3.0.5 on 2020-05-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teststep', models.CharField(max_length=10)),
                ('testcase', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=100)),
                ('status', models.IntegerField(max_length=10)),
                ('authkey', models.CharField(max_length=100)),
            ],
        ),
    ]
