# Generated by Django 3.0.5 on 2020-05-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.IntegerField(),
        ),
    ]
