# Generated by Django 3.0.5 on 2020-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200501_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='url',
            field=models.CharField(default='vikas.com', max_length=100),
        ),
    ]
