# Generated by Django 3.0.5 on 2020-05-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_test_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='teststep',
            field=models.CharField(choices=[('TC_1', 'TC_1'), ('TC_2', 'TC_2'), ('TC_3', 'TC_3')], max_length=10),
        ),
    ]
