# Generated by Django 3.0.5 on 2020-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20200502_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.IntegerField(choices=[('200', '200'), ('400', '400'), ('404', '404')]),
        ),
    ]
